
const ERROR_CODE_DEFAULT = 500;
const ERR_CODE_VALIDATION_ERROR = 400;
const ERR_CODE_NOT_FOUND = 404;


module.exports = {
  ERROR_CODE_DEFAULT,
  ERR_CODE_VALIDATION_ERROR,
  ERR_CODE_NOT_FOUND
};
